### ISSUE TITLE
Why .xls and .not csv?

### ISSUE THREAD

**Issue by todrobbins** [NYPL/ami-specifications#5]
I'm wondering why `.xls` was preferred over `.csv` for `hdmanifest` and `didnotcapture`.

**Comment by genfhk** [comment]
Hi Tod,
We chose .xls because our organization generally uses Excel to view and
process the manifests and other documentation we receive / create related
to digitization. Of course, .csv would also be a great format! We just
decided to stick with .xls.

Thanks for your inquiry!

**Comment by nkrabben** [comment]
Just wanted to add that those files aren't the final resting place for that information, so we just use the lowest common denominator in terms of what everyone is comfortable with across our staff and digitization vendors. To use the more important part is just standardizing the delivery of that information.

**Comment by todrobbins** [comment]
@genfhk @nkrabben thanks! That makes sense with the workflow and vendor environment. I really appreciate you making AMI an open spec/process.
